public with sharing class CampaignTriggerHandler {

    public CampaignTriggerHandler(){
    
    }
    /*  
    public void OnBeforeInsert(List<Campaign> newRecords){
    
    }
    
    public void OnAfterInsert(List<Campaign> newRecords){
        
    }
    
    @future public static void OnAfterInsertAsync(Set<ID> newRecordIDs){
        
    }
    
    public void OnBeforeUpdate(List<Campaign> oldRecords, List<Campaign> updatedRecords, Map<ID, Campaign> recordMap){
    }
    
    public void OnAfterUpdate(List<Campaign> oldRecords, List<Campaign> updatedRecords, Map<ID, Campaign> recordMap){
        
    }
    
    @future public static void OnAfterUpdateAsync(Set<ID> updatedRecordIDs){
        //List<Campaign> updatedCampaigns = [select Id, Name from Campaign where Id IN :updatedCampaignIDs];
    }
    
    public void OnBeforeDelete(List<Campaign> recordsToDelete, Map<ID, Campaign> recordMap){
        
    }
    
    public void OnAfterDelete(List<Campaign> deletedRecords, Map<ID, Campaign> recordMap){
        
    }
    
    @future public static void OnAfterDeleteAsync(Set<ID> deletedRecordIDs){
        
    }
    */
}