public with sharing class QuoteLineTriggerHandler {

    /*
     * Provisioned template. Most trigger events maintained in process builder and field update workflows.
     */
    public void OnBeforeInsert(List<SBQQ__QuoteLine__c> newRecords){
        
    }
    
    public void OnAfterInsert(List<SBQQ__QuoteLine__c> newRecords){
        
    }
    
    public void OnBeforeUpdate(List<SBQQ__QuoteLine__c> oldRecords, List<SBQQ__QuoteLine__c> updatedRecords, Map<ID, SBQQ__QuoteLine__c> recordMap){
        
    }
    
    public void OnAfterUpdate(List<SBQQ__QuoteLine__c> oldRecords, List<SBQQ__QuoteLine__c> updatedRecords, Map<ID, SBQQ__QuoteLine__c> recordMap){
        
    }
}